# This workflow will run tests using Node.js and then publish a package to GitHub Packages when a release is created.
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Run tests
on: [pull_request, push]

jobs:
  TestsAndInstall:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '16'
        
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test